<?xml version="1.0"?>

<!DOCTYPE data [
	<!ELEMENT history ((data)+)>
	<!ELEMENT data ((year,des,color)+)>
	<!ELEMENT year (#PCDATA)>
	<!ELEMENT des (#PCDATA)>
	<!ELEMENT color (#PCDATA)>
]>



<history>
		<data>
				<year>1800</year>
				<des>The Ojibwa Mide Ceremony that is a part of the Medewewin or Grand Medicine Society recorded their migration from Eastern Canada, the great Salt Sea, through the Great Lakes to the Prairies.  They departed their Great Town on the Salt Sea because of sickness and death.  They first moved to Moneaung (Montreal).  After a long period they moved to Lake Huron.  Again after a great period they moved to Boweting (Sault Ste Marie).  </des>
				<color>#0D0D0D</color>
		</data>	
		
		<data>
				<year>1802</year>
				<des>Indian maps convey much information where European documents fail.  The People draw maps in scale to travel time rather than an impractical mile scale.  A difficult river route occupies more space than easy ones of the same length, because it takes more time to travel.  French Canadian travel distance is calculated in night’s sleep where as the Metis, Coureurs de Bois, and Voyagers modified this system as pipes smoked.  The Ojibwa of Rainy Lake have a thriving business in the sale of wild rice to the fur trade.</des>
				<color>#1A1A1A</color>
		</data>	

		<data>
				<year>1804</year>
				<des>Peter Grant (1764-1848) a Northwest trader at Lac La Pluie wrote it is customary in winter for the tribes to break up into single family units.  This is a precaution necessary to their very existence.  They choose a particular hunting district and no other person will encroach upon it without a special invitation.  If they discover a beaver lodge they mark the situation and no other person would attempt to destroy it without permission.</des>
				<color>#262626</color>
		</data>	

		<data>
				<year>1805</year>
				<des>Lewis and Clark noted the Kalispel People (ear drop People) in northern Idaho.  They also visited the Kamiah People whom they called the Chopunnish People that numbered 800.  They are in fact a group of Nez Perce People.  The Klikitat a Shahaptian tribe who originally lived in Washington along the Lewis and White Rivers were noted by Lewis and Clark as living on the Yakima and Klickitat Rivers.  Lewis and Clark met the Klumaitumsh People who originally lived in Grays Harbor, Washington.  </des>
				<color>#333333</color>
		</data>	

		<data>
				<year>1806</year>
				<des>Meriweather Lewis met with the Blackfoot and made it very clear that the Americans came to establish peace between Indian tribes.  He stated the Americans intended to trade guns and ammunitions with the Shoshones and Nez Perces, mortal enemies of the Blackfoot.  Lewis and Reuben Field each killed a Blackfoot warrior.  This caused the Americans to be classed among the enemy of the Blackfoot, resulting in a 30 year standoff with much blood shed.  Most Americans dont appreciate the significant of this statement.</des>
				<color>#404040</color>
		</data>	

		<data>
				<year>1807</year>
				<des>A 42 man American Expedition into northwestern Montana is killed to the last man by the Blackfoot People.A trading post is built at the junction of the Yellowstone and Big Horn Rivers by Manuel Lisa a Spaniard from St. Louis.  He traded guns and ammunition with the Crow who were at war with the Blackfoot.Lisa retired in 1811 to the lower Missouri River area, founding the Missouri Fur Co.In case of famine any one may abandon his district and seek a better hunt on his neighbor's territory.</des>
				<color>#4C4C4C</color>
		</data>	
		<data>
				<year>1808</year>
				<des>June 14: At Cayoosh Flat (Lillooet, B.C.) the St'at'imc Nation debated to kill the (II)-Simon Frazer Party or to meet them in peace.  A consensus was finally reached for peace.  They welcomed the party into camp and provided them supplies.Following a naval victory over the Portuguese on December 24, 1808, negotiations were started developed into the opening of the first East India Company factory at Surat in 1613. It later grew to encompass much of western and central India.</des>
				<color>#595959</color>
		</data>	
		<data>
				<year>1810</year>
				<des>This year is remembered as the decline of the moose in Ojibwa Country some say as a result of over killing for the fur trade.  An Ojibwa band north of Lake Superior began to diminish in size.  By 1829 they are down to singular families that is better able to sustain themselves with small game.  Records of starvation among the People began to appear after this date. leaving the whole of this frontier exposed to the inroads and depredations of the enemy</des>
				<color>#666666</color>
		</data>	
		
		<data>
				<year>1811</year>
				<des>The battle of Beaver Dam on Twenty Mile Creek is summarized as follows; the Cognauga fought the battle, the Mohawk got the plunder and Lieutenant Fitzgibbon and De Haren who arrived with the regulars after the day had been won, claimed the credit.  The American General Peter B. Porter wrote disgustedly; the truth is we have had an army at Fort George for two months, this army lays panic-struck, shut up and held in by a few hundred miserable savages.</des>
				<color>#737373</color>
		</data>	
		
		<data>
				<year>1812</year>
				<des>A spokesperson of the Pillager band of Chippewa (Ojibwa) said he did not wish to mingle among quarrels between white men, nor did he intend ever to be guilty of breaking the window glass of the white man's dwelling.The War of 1812 was a 32-month military conflict between the United States of America and the United Kingdom of Great Britain and Ireland, its North American colonies and its Indian allies, but involved no boundary changes.</des>
				<color>#808080</color>
		</data>	
		
		<data>
				<year>1813</year>
				<des>The Native style of forest warfare is very different from the European line and siege type of warfare.  The Natives shamed Colonel Proctor into making a stand at Moravian Town on October 5, 1813.  Tecumseh and his men did the fighting and not Proctor and his Red Coats as claimed by some historians.  General Tecumseh, (1768-1813) the Shawnee war chief gave his life; Proctor saved his by flight.  This shameful action by the Red Coats discouraged the Peoples resistance in the Michigan and Lake Erie Region.</des>
				<color>#8C8C8C</color>
		</data>	
		
		<data>
				<year>1814</year>
				<des>The treaty of Ghent maintained the status quo with the Americans agreeing to restore all possessions rights and privileges to the People  The demand for clearly defined Indian Territory however is again frustrated.The Bannock People destroyed John Reids Trading Post on the lower Boise River Idaho.Resistance however continued in the upper reaches of Lake Huron and in Wisconsin. its North American colonies and its Indian allies</des>
				<color>#999999</color>
		</data>	
		
		<data>
				<year>1815</year>
				<des>The traders at India discovered how Maple Syrup is stored for later use.  The hyderabad made miniature barrels out of one piece of wood, sides and ends one piece, the interior being burnt out through the bung hole.  If the barrels are buried three feet deep it will keep a year or so. The history of Anglo-Indian relations was determined by the ... Two major events in the eighteenth century changed Britain's position in India.To organise this effectively meant that parliament had to regulate the company's </des>
				<color>#A6A6A6</color>
		</data>	
		
		<data>
				<year>1816</year>
				<des>This is recorded as the year without a summer.At San Francisco 300 Indians are dying annually from measles, cholera, smallpox and the Spanish disease of syphilis.The Year Without a Summer, a peculiar 19th century disaster, played out during 1816 when weather in Europe and North America took a bizarre turn that resulted in widespread crop failures and even famine.The weather in 1816 was bizarre. Spring came but then everything seemed to turn backward, as cold temperatures returned. The sky seemed permanently overcast. </des>
				<color>#B2B2B2</color>
		</data>	
		
		<data>
				<year>1817</year>
				<des>John Ross a Metis born October 3, 1790 of a Scottish father and a Cherokee mother died August 1, 1866.  He worked on the Cherokee Council this year to settle which lands the Cherokee would or would not have.  Later he himself was forced to a reservation,The United States acquired the Dakota’s through the Louisiana purchase .November 27:US soldiers attacked a Florida Indian village and started the first Seminole war. Andrew Jackson invaded Florida with 3,000 men forcing Spain to cede the land to the United States.  </des>
				<color>#BFBFBF</color>
		</data>	
		
		<data>
				<year>1818</year>
				<des>Manavadar (Bantva-Manavadar) becomes a British Protectorate, a Princely state which was founded in 1733.
							February - The Third Anglo-Maratha War which started in 1817 ends with the Marathas defeated by the British
							1 January - The Peshwa defeated at Koregaon by the British.6 January - Treaty of Mandasor is signed between the British and the Marathas.
							20 February - The Peshwa defeated at Ashti by the British
				</des>
				<color>#D9D9D9</color>
		</data>	
		
		<data>
				<year>1819</year>
				<des>The Ojibwa (Saulteaux) chief also known as William King born Sault Ste Marie 1774, died Red River September 28, 1864 and his children adopted the name Prince.  He defended the Selkirk settlers into Red River, showed them how to subsist in this country and later assisted the survivors after the seven oaks incident.  In gratitude the Selkirk settlers trespassed on his lands and violated the 1817 treaty with Selkirk..  

				</des>
				<color>#4C4C4C</color>
		</data>	
		
		<data>
				<year>1822</year>
				<des>The Ojibwa Shingwahkoonce spoke of the war of 1822, the storming of Mackinaw and the battle of Chippewa.  He spoke of the Ojibwa who lived on the English side of Sault Ste Marie and their forced removal to Manetowahning, on the north shore of Lake Huron.  Francis Broadhead, the snake, attempted to remove the Ojibwa of Sault Ste Marie to a barren island where soil is not good enough to raise potatoes or any other vegetable for their support.  The island they say is composed mostly of large rocks and stones.</des>
				<color>#808080</color>
		</data>	
		
		<data>
				<year>1823</year>
				<des>The Hon. John Adam, Governor-General, 1 Jan.-1 August.
				Lord Amherst, Governor-General, 1823-28.
				The Hon. John Adam, Governor-General, 1 Jan.-1 August.[1]
				Lord Amherst, Governor-General, 1823-28
				The minutes of the Court of Directors constitute the central record of the Company's activities in London. The stockholders' activities are recorded more briefly in the minutes of the Court of Proprietors.</des>
				<color>#1A1A1A</color>
		</data>	
		
		<data>
				<year>1824</year>
				<des>Red Jacket a Seneca was born 1756 Canoga, New York and died January 20, 1830 Buffalo, New York.  He spoke against the missionaries who lived among his people because they do us no good.  If they are not useful to the white people why do they send them to us.  Why do not you keep them home?  These Missionaries know that we do not understand their religion, we cannot read their books, they tell different stories about what it contains, these black coats tell us to raise corn and yet they do not themselves.   </des>
				<color>#0D0D0D</color>
		</data>	
		
		<data>
				<year>1825</year>
				<des>The Prairie du Chien Treaty of this year is alleged to have divided disputed territory between the Dakota Sioux and the Ojibwa.  Chief Shingabawossin of Sault Ste Marie, Wisconsin who signed the Governor Lewis Cass Treaty Du Chin is of the Businause Totem.  Chief Ahmous (little bee) son Waubishgauggauge (white crow) of the Lac Du Flambeau Band is also of the Businause Totem.  Chief Neokautah a Winnebago of Neenah, Wisconsin was a signer of the treaty.</des>
				<color>#1A1A1A</color>
		</data>	
		<data>
				<year>1828</year>
				<des>The Ojibwa of Michilimackinac are divided into two towns based on religion.  The Roman French Catholics separated from their brothers to form a new town encouraged by their priest.  This racist practice is encourage throughout the world by the various religious leaders and is very divisive.F.P. Wrangle reported the Koliuzh no longer attack the Russians out of fear.  This likely assumes the Russians made a major attack on these People.</des>
				<color>#262626</color>
		</data>	
		
		<data>
				<year>1829</year>
				<des>Nancy Shawanahdit, the last of the peace loving Beothuk Race (Red Indians) died at St. John, New Brunswick.  It was noted that she had previously suffered two gun shot wounds from earlier encounters.  The English had used her people as sport hunting targets.   The genocide war against her people by the French and English had ended.  The first Canadians to encountered the migrating Europeans are now extinct. Ralph Emerson said the name of this nation will stink to the world </des>
				<color>#333333</color>
		</data>	
		
		<data>
				<year>1830</year>
				<des>The American Indian removal Act order by President Andrew Jackson, a former Indian fighter, resulted in the relocation of 70,000 Indians from their ancestral lands east of the Mississippi River to the prairies. The Americans considered the plains desolate, fit only for Indians and the Federal Government did its best to put them there. The Indians would be squeezed onto smaller and smaller reservations. So many deaths resulted from the forced removal that it became known as the trail of tears. .  </des>
				<color>#404040</color>
		</data>	
		
		<data>
				<year>1835</year>
				<des>28 January - Medical College, Bengal is established; later became Medical College Kolkata.
				2 February - Madras Medical College is established.Lord Macaulay said the following about India in 1835 in British Parliament.the correct year was 1833 or 1835, but what matters for Indians is the statement itself the first selection a speech on the India bill.From Thomas Babington Macaulay, "Minute of 2 February 1835 </des>
				<color>#4C4C4C</color>
		</data>	
		
		<data>
				<year>1836</year>
				<des>Some suggest the Seminole War (1836-1842) started this year at a cost of twenty million dollars and the death of 1,500 soldiers.  The only effective method used to capture the Seminole was to lure small groups in for parley under the sacred immunity of a flag of truce, then seize them.  They sent 4,000 captured Seminole on the Trail of Tears.  The Americans called off the war as only a few hundred Seminole remained in the swamps.</des>
				<color>#595959</color>
		</data>	
		
		<data>
				<year>1837</year>
				<des>A longboat was sent from Fort Union to Fort McKenzie on the Maris River in upper Missouri River region.  The fort was warned but a quarantine could not be maintained.  The disease spread to 500 lodges of Blackfoot and Piegan (some 5,500 people) at Fort McKenzie.  In this way the disease spread throughout the Missouri River Valley.  The People believed they could run away from the disease and the Assiniboine, Cree, Blood, Blackfoot and Piegan fled north and spread the disease into Canada.  </des>
				<color>#666666</color>
		</data>

		<data>
				<year>1842</year>
				<des>The first Mission at Red Lake by Rev. Frederick Ayres who left Brainerd Spencer in charge. It was abandoned in 1859. The Red Lake Ojibwa raised a significant surplus of grain and vegetables enough to feed fifty families from other bands who wintered 1842-43 at Red Lake to escape starvation in their home areas. In the summer they join the Red River Metis in their bison buffalo hunts.Walton, George H. Fearless and Free: the Seminole Indian War,1835-1842. Indianapolis, </des>
				<color>#737373</color>
		</data>		
		
		<data>
				<year>1843</year>
				<des>There was still a surplus of grain available at Red Lake as $100.00 worth was purchased by Alfred Brunson, Sub-Agent at La Pointe, Wisconsin for distribution to the Ojibwa of other areas.William Sublette, fur trader, led a party of pleasure hunters out into the plains from St. Louis. Among the party was the Scottish nobleman Captain Sir William Drummond Stewart and William Clark Kennerly with eighty men. They left the prairie strewan for miles with the bodies of dead bison (buffalo).</des>
				<color>#808080</color>
		</data>		
		
		<data>
				<year>1844</year>
				<des>Bishop George Mountain reported from Red River that native cult objects represent tangible proof of imposture, delusion and darkness.  Father LeJeunne believed the wicked liberty of the savages needs the yoke of god to prevent them from following their inclination.Ojaouanon a Chief of Walpole Island debated with Jesuit Superior Pierre Chazelle.  The Great Spirit sees and knows everything, taught the elders who teach the people and we keep it in our hearts and will never renounce our faith.</des>
				<color>#8C8C8C</color>
		</data>		
		
		<data>
				<year>1845</year>
				<des>1st Sikh War, 1845-46.
				Grant Medical College opened in Bombay.The Sikh kingdom of Punjab was expanded and consolidated by Maharajah Ranjit Singh during the early years of the nineteenth century, about the same time as the British-controlled territories were advanced by conquest or annexation to the borders of the Punjab.He hired American and European mercenary soldiers to train his artillery.</des>
				<color>#999999</color>
		</data>		
		
		<data>
				<year>1846</year>
				<des>At Sault Ste Marie on the American side lives seven to eight hundred People whereas on the Canadian side there are only a few Metis and many Ojibwa.  A census by J.P. Hays, a sub agent from La Pointe Wisconsin placed the Red Lake clan as 1,200 being located at Pembina, Red Lake and Winnipeg Lakes.  He said their main substance is agriculture producing 2,000 bushels corn.  No mention is made of the other crops.  In winter they hunt bison buffalo west of the Red River. </des>
				<color>#A6A6A6</color>
		</data>		
		
		<data>
				<year>1848</year>
				<des>2nd Sikh War, 1848-49.Annexation of Sattara.2nd Sikh War, 1848-49.The California Gold Rush (1848–1855) began on January 24, 1848, when gold was found by James W. Marshall at Sutter's Mill in Coloma, California.[1] The first to hear confirmed information of the Gold Rush were the people in Oregon, the Sandwich Islands (Hawaii), and Latin America.Gold mining also caused environmental harm to rivers and lakes.</des>
				<color>#B2B2B2</color>
		</data>		
		
		<data>
				<year>1849</year>
				<des>2nd Sikh War, 1848-49.
				Annexation of Punjab.
				Annexation of Jaitpur and Sambalpur.
				Find 4 collections in India from 1840-1849 at WorldVitalRecords.com.Please select one of the decades below to get access to all the family history resources we have for India for a given time period.But by 1849, during the gold rush, the non-Indian population of California had grown to 100,000.</des>
				<color>#BFBFBF</color>
		</data>		
		
		<data>
				<year>1850</year>
				<des>The ceremony of turning the first sod for the Great Indian Peninsula Railway from Mumbai to Kalyan was performed by J. P. Willoughby at a place near Sion.The Michigan Constitution read :Neither slavery nor involuntary servitude, unless for the punishment of crime, shall be tolerated in this state."  Some believe they didn't realize this constitution legalized slavery until 1963 when it was finally revoked.</des>
				<color>#CCCCCC</color>
		</data>		
		
		<data>
				<year>1852</year>
				<des>Katimin a village of the Karok People on the banks of the Klamath River about a mile from the mouth of the Salmon River in California is burned by the white people.  The Karok believed this location was the center of the earth and was a very sacred area.  It was the scene of many yearly ceremonies.It offers students the opportunity to study the history of 19th-century India and its imperial contexts in greater depth.</des>
				<color>#D9D9D9</color>
		</data>		
		
		<data>
				<year>1853</year>
				<des>April 16 - The first Indian train popularly called Aag Gadi which steamed off from Bombay to Thane. The train was drawn by three engines and covered the 34km distance in 57 minutes.There are no prerequisites for this module, but as a History ‘special subject’ it is designed to build upon work students have done in their first and second years, especially in relation to the history of imperialism and South Asia including the core course "Making of the Modern World"</des>
				<color>#737373</color>
		</data>		
		
		<data>
				<year>1856</year>
				<des>25 July - Hindu Widows' Remarriage Act, 1856
				Annexation of the Kingdom of Oudh
				The Indian Rebellion of 1857 began as a mutiny of sepoys of the East India Company's army on 10 May 1857, in the town of Meerut, and soon escalated into other mutinies and civilian rebellions largely in the upper Gangetic plain and central India, with the major hostilities confined to present-day Uttar Pradesh, Bihar, northern Madhya Pradesh, and the Delhi region</des>
				<color>#999999</color>
		</data>		
		
		<data>
				<year>1857</year>
				<des>10 May (starting date of the revolt)- Indian rebellion of 1857 (also known as the Sepoy Mutiny) or The First War Of Indian Independence, widespread uprising in northern and central India against the rule of the British East India Company.the Revolt of 1857, the Uprising of 1857, the Sepoy Rebellion and the Sepoy Mutiny. The Mutiny was a result of various grievances. However the flashpoint was reached when the soldiers were asked to bite off the paper cartridges for their rifles which they believed.</des>
				<color>#B2B2B2</color>
		</data>		
		
	
		<data>
				<year>1858</year>
				<des>February - General Rose relieves Saugor; Campbell's Army of Oudh assembles on the Kanpur-Lucknow road to await Jang Bahadur's Gurkha army
				March - Lucknow is recaptured on 21 March; Central India campaign continuesIndian Rebellion of 1857 urged British Government to pass this Act. To calm down the after effects of 1857 revolt, the Act of 1858 was introduced.The Company's territories in India were to be vested in the Queen</des>
				<color>#0D0D0D</color>
		</data>		
		
		<data>
				<year>1859</year>
				<des>The Indian rebellion of 1857 ends (formally declared in July).Execution of Tatya Tope (Ramachandra Pandurang Tope), 18 April 1859, a Maratha leader in the Indian Rebellion of 1857.January - General Sir Hugh Rose begins the Central India campaign Sir Colin Campbell begins the campaign to recapture Lucknow; trial of Bahadur Shah, King of Delhi, from 27 January
				 the Company ceasing to exercise its power</des>
				<color>#1A1A1A</color>
		</data>		
		
		<data>
				<year>1860</year>
				<des>Later, on the annual bison (buffalo) hunt, the White Horse Plains Metis visited the Dakota Sioux village of 1,500 warriors to make peace.  The Dakota Sioux had sent a peace party to the Metis camp requesting a conference.  Following peace, the Dakota Sioux performed the bison (buffalo) Head Dance.  In the evening the young single girls, in white deer skin, profusely ornamented with porcupine quills and beads, danced and sung much to the enjoyment of the young Metis hunters, who made many presents.</des>
				<color>#262626</color>
		</data>		
		
		<data>
				<year>1861</year>
				<des>Boys' High School and College, Allahabad, is founded.In the evening the young single girls, in white deer skin, profusely ornamented with porcupine quills and beads
				The Delhi Department of Police is founded. Rabindranath Tagore, poet, artist, playwright, novelist and composer24 September: Bhikaiji Cama, independence campaigner (died 1936).Date unknown: Devaki Nandan Khatri, first author of mystery novels in Hindi (died 1913)</des>
				<color>#333333</color>
		</data>		
		
		<data>
				<year>1862</year>
				<des>Senator Ramsey of Minnesota met with 2,000 Red Lake Ojibwa to conclude the 1862 treaty that is deferred due to the Sibley War.  The settlement would cost ten million dollars.  Alexander Ramsey also entered into treaty with the Chippewa (Ojibwa) of Pembina and Turtle Mountain who are descendents of Red Lake.  They previously descended from the Lake Superior Ojibwa.  No distinction is made between Indian and Metis at this time.fter two years of killing and plundering on July 28 at Killdeer Mountain</des>
				<color>#4C4C4C</color>
		</data>		
		
		<data>
				<year>1863</year>
				<des>Senator Ramsey of Minnesota met with 2,000 Red Lake Ojibwa to conclude the 1862 treaty that is deferred due to the Sibley War.  The settlement would cost ten million dollars.  Alexander Ramsey also entered into treaty with the Chippewa (Ojibwa) of Pembina and Turtle Mountain who are descendents of Red Lake.  They previously descended from the Lake Superior Ojibwa.  No distinction is made between Indian and Metis at this time.</des>
				<color>#4C4C4C</color>
		</data>		
		
		<data>
				<year>1864</year>
				<des>After two years of killing and plundering on July 28 at Killdeer Mountain that is South East of Watford, North Dakota the 2,200 man army led by Sully attacked a Dakota village massacring 100 to 150 people.  The prospectors and miners in Shasta and Tehama Counties in California slaughtered 2,950 Yana People men, women and children within a few days with only 50 escaping bringing these people to extinction as a tribe.</des>
				<color>#595959</color>
		</data>		
		
		<data>
				<year>1866</year>
				<des>History of Norwich, Connecticut: From Its Possession by the Indians, to the Year 1866
				17 August - Mahbub Ali Khan was born, Asaf Jah VI, sixth Nizam of Hyderabad (died 1911).The History has been entirely re-written, and is, in fact, a new work. The author has considered it an imperative duty to review all the sources of information, and to make it as complete a town history as the materials would permit.Annual report of the commissioner of Indian affairs, for the year 1878.</des>
				<color>#666666</color>
		</data>		
		
		<data>
				<year>1868</year>
				<des>Bank of Bombay established.Earthquake in Ahmedabad, Bombay State.
				The Indian Councils Act 1861 was an Act of the Parliament of the United Kingdom that transformed the Viceroy of India's executive council into a cabinet run on the portfolio system.The Governor General was given the power to create new provinces for legislative purposes
				The History of Norwich, published in 1845, having been for several years out of print, it seems desirable that the public should be furnished with a new and more complete work</des>
				<color>#737373</color>
		</data>		
		
		<data>
				<year>1869</year>
				<des>Sir John Lawrence, Viceroy
				Richard Bourke, 6th Earl of Mayo, Viceroy 
				La Martinière Girls School is founded in Lucknow.
				11 April - Kasturba Gandhi, wife of Mohandas Karamchand Gandhi .
				2 October  Mohandas Karamchand Gandhi, political and spiritual leader in India and the Indian independence movement  ,assassinated .</des>
				<color>#808080</color>
		</data>		
		
		<data>
				<year>1870</year>
				<des>The first submarine telegraph cable from UK landed in Bombay.
				The United Service Institution (USI) was founded.
				January 3 – Construction of the Brooklyn Bridge begins.
				January 6 – The Musikverein, Vienna is inaugurated in Austria-Hungary.
				January 10 – John D. Rockefeller incorporates Standard Oil.
				January 15 – A political cartoon for the first time symbolizes the United States Democratic Party with a donkey ("A Live Jackass Kicking a Dead Lion" by Thomas Nast for Harper's Weekly).</des>
				<color>#8C8C8C</color>
		</data>		
		
		<data>
				<year>1871</year>
				<des>October 12-Criminal Tribes Act (CTA) enacted by British rule in India, which named over 160 communities "Criminal Tribes", i.e. hereditary criminals. It was repealed in 1949, after Independence of India.October 12 – Criminal Tribes Act (CTA) enacted by British rule in India, which named over 160 communities "Criminal Tribes", i.e. hereditary criminals. It was repealed in 1949, after Independence of India</des>
				<color>#999999</color>
		</data>		
		
		<data>
				<year>1872</year>
				<des>BIRTHS

				14 April - Abdullah Yusuf Ali, Islamic scholar who translated the Qur'an into English (died 1953).
	A political cartoon for the first time symbolizes the United States Democratic Party with a donkey ("A Live Jackass Kicking a Dead Lion"			15 August - Sri Aurobindo, nationalist, scholar, poet, mystic, evolutionary philosopher, yogi and guru (died 1950).
				 Partnership contained in the Indian Contract Act were repealed respectively in the year 1930 and 1932 </des>
				<color>#A6A6A6</color>

				</data>		
		
		<data>
				<year>1873</year>
				<des>Incumbents

				Thomas Baring, 1st Earl of Northbrook, Viceroy
				Events

				Bihar famine of 1873–74
				Births

					19 December - Upendranath Brahmachari, scientist and medical practitionerJan 1st - Origin of Japanese Era
Jan 6th - Pope Pius IX encyclical "On the Church in Armenia"
Jan 6th - US Congress begins investigating Crédit Mobilier scandal
Jan 11th - 1st livestock market newspaper published, Drover's Journal, Chicago</des>
				<color>#B2B2B2</color>
		</data>		
		
		<data>
				<year>1874</year>
				<des>Bihar famine of 1873-74
				The Prince of Wales visits British India.
				January - The Pangkor Treaty (also known as the Pangkor Engagement), by which the British extended their control over, first the Sultanate of Perak and later the other independent Malay States, is signed.
January 1 - New York City annexes The Bronx.
</des>
				<color>#BFBFBF</color>
		</data>		
		
		<data>
				<year>1875</year>