<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="test.xsl" ?>
<!DOCTYPE data [
	<!ELEMENT history ((tv18)+)>
	<!ELEMENT data ((imglink,header,des,link)+)>
	<!ELEMENT imglink (#PCDATA)>
	<!ELEMENT header (#PCDATA)>
	<!ELEMENT des (#PCDATA)>
	<!ELEMENT link (#PCDATA)>
]>



<history>
		<tv18>
				<imglink>http://www.historyindia.com/sites/default/files/styles/shows_thumbnail/public/passage%20through%20india_thumb.jpg</imglink>
				<header>A PASSAGE THROUGH INDIA</header>
				<des>A unique travelogue with a refreshing new perspective on India</des>
				<link>http://www.historyindia.com/shows/passage-through-india</link>
		</tv18>	
		
		<tv18>
				<imglink>http://www.historyindia.com/sites/default/files/styles/shows_thumbnail/public/thumb_107.jpg</imglink>
				<header>AIR INDIA</header>
				<des>Bombing of Air India 182</des>
				<link>http://www.historyindia.com/shows/79195</link>
		</tv18>	
		
		<tv18>
				<imglink>http://www.historyindia.com/sites/default/files/styles/shows_thumbnail/public/thumb_57.jpg</imglink>
				<header> BIRMINGHAM TO BOMBAY </header>
				<des>From Birmingham to Bombay looks at the global love affair of Indian food and curries</des>
				<link>http://www.historyindia.com/shows/69565</link>
		</tv18>	
		
		<tv18>
				<imglink>http://www.historyindia.com/sites/default/files/styles/shows_thumbnail/public/thumb_54.jpg</imglink>
				<header>INDIA ON FOUR WHEELS</header>
				<des>Justin Rowlett and Anita Rani join the chaos of India's roads on a madcap road trip across the country, to find out the truth behind the dream of owning a car.</des>
				<link>http://www.historyindia.com/shows/65991</link>
		</tv18>	
		
		<tv18>
				<imglink>http://www.historyindia.com/sites/default/files/styles/shows_thumbnail/public/thumb_51.jpg</imglink>
				<header>TAJ MAHAL</header>
				<des>Searching for clues to the original Taj Mahal and investigate the myth of a second Taj Mahal, built not in white but in black marble.</des>
				<link>http://www.historyindia.com/shows/67703</link>
		</tv18>	
		
		<tv18>
				<imglink>http://www.historyindia.com/sites/default/files/styles/shows_thumbnail/public/tamas_0.jpg</imglink>
				<header>TAMAS</header>
				<des>The greatest story of India's partition</des>
				<link>http://www.historyindia.com/shows/91837</link>
		</tv18>	
		
	
</history>